version: '3'

services:
  component-locator:
    container_name: component-locator
    restart: always
    build: ./component-locator
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - component-locator